#ifndef SIDETNFS_CONFIG_DRIVE_H
#define SIDETNFS_CONFIG_DRIVE_H

#include <stdint.h>

// Fase 10A: byte-exact copies of the SideTNFS configuration drive's
// contents (SIDETNFS.PRG and README.TXT), embedded in Pico flash so this
// drive is always available -- no SD card, no TNFS server needed. Plain
// const uint8_t arrays: no endian conversion, no word-packing (unlike
// firmwareROM/gemdrvemulROM etc. in firmware.c/firmware_gemdrvemul.c,
// which hold 16-bit Atari ROM images and are intentionally word-packed).
// Generated by download_sidetnfs_config_drive.py into
// sidetnfs_config_drive.c, which -- like firmware.c -- is committed so
// offline builds stay reproducible; the generator is not run
// automatically by the build. No GEMDRIVE/configdrive backend reads these
// yet (Fase 10A only proves the bytes reach flash intact) -- nothing in
// this phase copies these arrays to RAM.
extern const uint8_t sidetnfs_config_prg[];
extern const uint32_t sidetnfs_config_prg_length;

extern const uint8_t sidetnfs_config_readme[];
extern const uint32_t sidetnfs_config_readme_length;

// Combined content must fit in a conservative flash budget -- generous
// headroom before it could ever threaten CONFIG_FLASH_OFFSET (0xDE000,
// see romemul/memmap_romemul.ld and romemul/constants.c). Checked via
// _Static_assert in sidetnfs_config_drive.c, where the array sizes are
// actually known at compile time.
#define SIDETNFS_CONFIG_DRIVE_MAX_TOTAL_BYTES (256u * 1024u)

// GEMDOS file sizes (e.g. the Fsfirst/Fsnext DTA's d_length, and Fread's
// byte-count arguments) are 32-bit values on real hardware, but this
// project's own GEMDOS layer already caps meaningful sizes well under
// that -- 16 MiB is a conservative, still-enormous ceiling no real
// SIDETNFS.PRG/README.TXT could plausibly reach, chosen so a build-time
// mistake (e.g. accidentally embedding the wrong file) is caught here
// rather than surfacing as a GEMDOS truncation bug later.
#define SIDETNFS_CONFIG_DRIVE_MAX_FILE_BYTES (16u * 1024u * 1024u)

#endif // SIDETNFS_CONFIG_DRIVE_H
