#ifndef COMMANDS_H_
#define COMMANDS_H_

#define APP_CONFIGURATOR 0x00
#define APP_ROMEMUL 0x01
#define APP_FLOPPYEMUL 0x02
#define APP_RTCEMUL 0x03
#define APP_GEMDRVEMUL 0x04

// APP_GEMDRVEMUL commands
#define GEMDRVEMUL_PING (APP_GEMDRVEMUL << 8 | 0)
#define GEMDRVEMUL_SAVE_VECTORS (APP_GEMDRVEMUL << 8 | 1)
#define GEMDRVEMUL_SHOW_VECTOR_CALL (APP_GEMDRVEMUL << 8 | 2)
#define GEMDRVEMUL_REENTRY_LOCK (APP_GEMDRVEMUL << 8 | 3)
#define GEMDRVEMUL_REENTRY_UNLOCK (APP_GEMDRVEMUL << 8 | 4)
#define GEMDRVEMUL_CANCEL (APP_GEMDRVEMUL << 8 | 5)

#define GEMDRVEMUL_SAVE_XBIOS_VECTOR   (APP_GEMDRVEMUL << 8 | 10)
#define GEMDRVEMUL_REENTRY_XBIOS_LOCK  (APP_GEMDRVEMUL << 8 | 11)
#define GEMDRVEMUL_REENTRY_XBIOS_UNLOCK (APP_GEMDRVEMUL << 8 | 12)

#define GEMDRVEMUL_DGETDRV_CALL (APP_GEMDRVEMUL << 8 | 0x19)
#define GEMDRVEMUL_FSETDTA_CALL (APP_GEMDRVEMUL << 8 | 0x1A)
#define GEMDRVEMUL_DFREE_CALL (APP_GEMDRVEMUL << 8 | 0x36)
#define GEMDRVEMUL_DCREATE_CALL (APP_GEMDRVEMUL << 8 | 0x39)
#define GEMDRVEMUL_DDELETE_CALL (APP_GEMDRVEMUL << 8 | 0x3A)
#define GEMDRVEMUL_DSETPATH_CALL (APP_GEMDRVEMUL << 8 | 0x3B)
#define GEMDRVEMUL_FCREATE_CALL (APP_GEMDRVEMUL << 8 | 0x3C)
#define GEMDRVEMUL_FOPEN_CALL (APP_GEMDRVEMUL << 8 | 0x3D)
#define GEMDRVEMUL_FCLOSE_CALL (APP_GEMDRVEMUL << 8 | 0x3E)
#define GEMDRVEMUL_FDELETE_CALL (APP_GEMDRVEMUL << 8 | 0x41)
#define GEMDRVEMUL_FSEEK_CALL (APP_GEMDRVEMUL << 8 | 0x42)
#define GEMDRVEMUL_FATTRIB_CALL (APP_GEMDRVEMUL << 8 | 0x43)
#define GEMDRVEMUL_DGETPATH_CALL (APP_GEMDRVEMUL << 8 | 0x47)
#define GEMDRVEMUL_PEXEC_CALL   (APP_GEMDRVEMUL << 8 | 0x4B)
#define GEMDRVEMUL_FSFIRST_CALL (APP_GEMDRVEMUL << 8 | 0x4E)
#define GEMDRVEMUL_FSNEXT_CALL (APP_GEMDRVEMUL << 8 | 0x4F)
#define GEMDRVEMUL_FDATETIME_CALL (APP_GEMDRVEMUL << 8 | 0x57)

#define GEMDRVEMUL_FWRITE_CALL    (APP_GEMDRVEMUL << 8 | 0x40)  // never sent by ROM — dead
#define GEMDRVEMUL_FRENAME_CALL   (APP_GEMDRVEMUL << 8 | 0x56)
#define GEMDRVEMUL_READ_BUFF_CALL (APP_GEMDRVEMUL << 8 | 0x81)
#define GEMDRVEMUL_SET_SHARED_VAR (APP_GEMDRVEMUL << 8 | 0x87)
#define GEMDRVEMUL_FWRITE_BUFF_CALL (APP_GEMDRVEMUL << 8 | 0x88) // write-data upload
#define GEMDRVEMUL_FWRITE_ACK_CALL  (APP_GEMDRVEMUL << 8 | 0x89) // write-chunk ack
#define GEMDRVEMUL_DTA_EXIST_CALL (APP_GEMDRVEMUL << 8 | 0x8A)
#define GEMDRVEMUL_DTA_RELEASE_CALL (APP_GEMDRVEMUL << 8 | 0x8B)

#endif // COMMANDS_H_
