#ifndef GEMDRVEMUL_H
#define GEMDRVEMUL_H

#include "debug.h"
#include "constants.h"
#include "firmware_gemdrvemul.h"

#include <inttypes.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/structs/bus_ctrl.h"

#include "tprotocol.h"
#include "commands.h"
#include "memfunc.h"

#define MAX_FOLDER_LENGTH 128

#define DEFAULT_FOPEN_READ_BUFFER_SIZE 16384
#define DEFAULT_FWRITE_BUFFER_SIZE     2048
#define FIRST_FILE_DESCRIPTOR 16384
#define DTA_SIZE_ON_ST 44
#define SHARED_VARIABLES_SIZE 7

#define SHARED_VARIABLE_FIRST_FILE_DESCRIPTOR (SHARED_VARIABLE_SHARED_FUNCTIONS_SIZE + 0)
#define SHARED_VARIABLE_DRIVE_LETTER          (SHARED_VARIABLE_SHARED_FUNCTIONS_SIZE + 1)
#define SHARED_VARIABLE_DRIVE_NUMBER          (SHARED_VARIABLE_SHARED_FUNCTIONS_SIZE + 2)
#define SHARED_VARIABLE_PEXEC_RESTORE         (SHARED_VARIABLE_SHARED_FUNCTIONS_SIZE + 3)
#define SHARED_VARIABLE_FAKE_FLOPPY           (SHARED_VARIABLE_SHARED_FUNCTIONS_SIZE + 4)

// Shared memory offsets (relative to ROM3_START_ADDRESS)
#define GEMDRVEMUL_RANDOM_TOKEN        (0x0000)
#define GEMDRVEMUL_RANDOM_TOKEN_SEED   (GEMDRVEMUL_RANDOM_TOKEN + 4)
#define GEMDRVEMUL_TIMEOUT_SEC         (GEMDRVEMUL_RANDOM_TOKEN_SEED + 4)
#define GEMDRVEMUL_PING_STATUS         (GEMDRVEMUL_TIMEOUT_SEC + 4)
#define GEMDRVEMUL_RTC_STATUS          (GEMDRVEMUL_PING_STATUS + 4)
#define GEMDRVEMUL_NETWORK_STATUS      (GEMDRVEMUL_RTC_STATUS + 8)
#define GEMDRVEMUL_RTC_ENABLED         (GEMDRVEMUL_NETWORK_STATUS + 4)
#define GEMDRVEMUL_REENTRY_TRAP        (GEMDRVEMUL_RTC_ENABLED + 8)
#define GEMDRVEMUL_OLD_XBIOS_TRAP      (GEMDRVEMUL_REENTRY_TRAP + 4)
#define GEMDRVEMUL_RTC_XBIOS_REENTRY_TRAP (GEMDRVEMUL_OLD_XBIOS_TRAP + 4)
#define GEMDRVEMUL_RTC_DATETIME_BCD    (GEMDRVEMUL_RTC_XBIOS_REENTRY_TRAP + 4)
#define GEMDRVEMUL_RTC_DATETIME_MSDOS  (GEMDRVEMUL_RTC_DATETIME_BCD + 8)
#define GEMDRVEMUL_RTC_Y2K_PATCH       (GEMDRVEMUL_RTC_DATETIME_MSDOS + 8)

#define GEMDRVEMUL_DEFAULT_PATH        (GEMDRVEMUL_RTC_Y2K_PATCH + 4)
#define GEMDRVEMUL_DTA_F_FOUND         (GEMDRVEMUL_DEFAULT_PATH + 128)
#define GEMDRVEMUL_DTA_TRANSFER        (GEMDRVEMUL_DTA_F_FOUND + 4)
#define GEMDRVEMUL_DTA_EXIST           (GEMDRVEMUL_DTA_TRANSFER + DTA_SIZE_ON_ST)
#define GEMDRVEMUL_DTA_RELEASE         (GEMDRVEMUL_DTA_EXIST + 4)
#define GEMDRVEMUL_SET_DPATH_STATUS    (GEMDRVEMUL_DTA_RELEASE + 4)
#define GEMDRVEMUL_FOPEN_HANDLE        (GEMDRVEMUL_SET_DPATH_STATUS + 4)

#define GEMDRVEMUL_READ_BYTES          (GEMDRVEMUL_FOPEN_HANDLE + 4)
#define GEMDRVEMUL_READ_BUFF           (GEMDRVEMUL_READ_BYTES + 4)
#define GEMDRVEMUL_WRITE_BYTES         (GEMDRVEMUL_READ_BUFF + DEFAULT_FOPEN_READ_BUFFER_SIZE)
#define GEMDRVEMUL_WRITE_CHK           (GEMDRVEMUL_WRITE_BYTES + 4)
#define GEMDRVEMUL_WRITE_CONFIRM_STATUS (GEMDRVEMUL_WRITE_CHK + 4)

#define GEMDRVEMUL_FCLOSE_STATUS       (GEMDRVEMUL_WRITE_CONFIRM_STATUS + 4)
#define GEMDRVEMUL_DCREATE_STATUS      (GEMDRVEMUL_FCLOSE_STATUS + 4)
#define GEMDRVEMUL_DDELETE_STATUS      (GEMDRVEMUL_DCREATE_STATUS + 4)
#define GEMDRVEMUL_EXEC_HEADER         (GEMDRVEMUL_DDELETE_STATUS + 4)
#define GEMDRVEMUL_FCREATE_HANDLE      (GEMDRVEMUL_EXEC_HEADER + 32)
#define GEMDRVEMUL_FDELETE_STATUS      (GEMDRVEMUL_FCREATE_HANDLE + 4)
#define GEMDRVEMUL_FSEEK_STATUS        (GEMDRVEMUL_FDELETE_STATUS + 4)
#define GEMDRVEMUL_FATTRIB_STATUS      (GEMDRVEMUL_FSEEK_STATUS + 4)
#define GEMDRVEMUL_FRENAME_STATUS      (GEMDRVEMUL_FATTRIB_STATUS + 4)
#define GEMDRVEMUL_FDATETIME_DATE      (GEMDRVEMUL_FRENAME_STATUS + 4)
#define GEMDRVEMUL_FDATETIME_TIME      (GEMDRVEMUL_FDATETIME_DATE + 4)
#define GEMDRVEMUL_FDATETIME_STATUS    (GEMDRVEMUL_FDATETIME_TIME + 4)
#define GEMDRVEMUL_DFREE_STATUS        (GEMDRVEMUL_FDATETIME_STATUS + 4)
#define GEMDRVEMUL_DFREE_STRUCT        (GEMDRVEMUL_DFREE_STATUS + 4)

#define GEMDRVEMUL_PEXEC_MODE          (GEMDRVEMUL_DFREE_STRUCT + 32)
#define GEMDRVEMUL_PEXEC_STACK_ADDR    (GEMDRVEMUL_PEXEC_MODE + 4)
#define GEMDRVEMUL_PEXEC_FNAME         (GEMDRVEMUL_PEXEC_STACK_ADDR + 4)
#define GEMDRVEMUL_PEXEC_CMDLINE       (GEMDRVEMUL_PEXEC_FNAME + 4)
#define GEMDRVEMUL_PEXEC_ENVSTR        (GEMDRVEMUL_PEXEC_CMDLINE + 4)

#define GEMDRVEMUL_SHARED_VARIABLES    (GEMDRVEMUL_PEXEC_ENVSTR + 4)

// FATTRIB flags
#define FATTRIB_INQUIRE 0x00
#define FATTRIB_SET     0x01

// FDATETIME flags
#define FDATETIME_INQUIRE 0x00
#define FDATETIME_SET     0x01

// GEMDOS error codes
#define GEMDOS_EOK     0
#define GEMDOS_ERROR  -1
#define GEMDOS_EDRVNR -2
#define GEMDOS_EINVFN -32
#define GEMDOS_EFILNF -33
#define GEMDOS_EPTHNF -34
#define GEMDOS_ENHNDL -35
#define GEMDOS_EACCDN -36
#define GEMDOS_EIHNDL -37
#define GEMDOS_EDRIVE -46
#define GEMDOS_ENMFIL -49
#define GEMDOS_EINTRN -65

typedef void (*IRQInterceptionCallback)();

extern int read_addr_rom_dma_channel;
extern int lookup_data_rom_dma_channel;

void __not_in_flash_func(gemdrvemul_dma_irq_handler_lookup_callback)(void);

void init_gemdrvemul(void);

#endif // GEMDRVEMUL_H
